dataset_name: alexliap/tinystories-gr
text_column: greek_translation
val_size: 0.01
seed: 42
profile_vocab_sizes: [4000, 8000, 12000, 16000]
final_vocab_size: 8000
min_frequency: 2
profile_train_subset: 50000
profile_eval_subset: 5000
